### ISSUE TITLE
实现获取js-sdk签名, 代码如下, 报错了

### ISSUE THREAD

**Issue by lmj2577977814** [Wechat-Group/weixin-java-open-demo#37]
WxMpService mpService = this.wxOpenServiceDemo.getWxOpenComponentService().getWxMpServiceByAppid(appId);
        try {
            WxJsapiSignature jsapiSignature = mpService.createJsapiSignature(url);
            return ResponseUtil.buildSuccess(jsapiSignature);
        } catch (WxErrorException e) {
            e.printStackTrace();
        }

Caused by: java.lang.AbstractMethodError: me.chanjar.weixin.open.api.impl.WxOpenInMemoryConfigStorage$WxOpenInnerConfigStorage.getTicketLock(Lme/chanjar/weixin/mp/enums/TicketType;)Ljava/util/concurrent/locks/Lock;
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getTicket(BaseWxMpServiceImpl.java:95)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.getJsapiTicket(BaseWxMpServiceImpl.java:124)
	at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.createJsapiSignature(BaseWxMpServiceImpl.java:131)
	at cn.casair.wx.rest.WxMpUserController.getSignature(WxMpUserController.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	... 102 common frames omitted

**Comment by binarywang** [comment]
这种错误，明显是版本冲突导致的，建议自己检查下

**Comment by lmj2577977814** [comment]
解决了,换了版本好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/weixin-java-open-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 中午11:35
收件人:&nbsp;"Wechat-Group/weixin-java-open-demo"<weixin-java-open-demo@noreply.github.com&gt;;
抄送:&nbsp;"...."<2577977814@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/weixin-java-open-demo] 实现获取js-sdk签名, 代码如下, 报错了 (#37)





 
这种错误，明显是版本冲突导致的，建议自己检查下
